import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// Make the server wait for my input to continue
		System.in.read();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.xx"));

		Key key = null;

		key = (Key) in.readObject();

		in.close();

		// -Use the key to decrypt the incoming message from socket s.
		Cipher dcipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
		dcipher.init(Cipher.DECRYPT_MODE, key);

		CipherInputStream dcipherIn = new CipherInputStream(s.getInputStream(), dcipher);

		ByteArrayOutputStream os = new ByteArrayOutputStream();

		File file = new File("KeyFile.xx");

		byte[] buf = new byte[(int) file.length()];


		// int bytesRead = 0;
		// int bytesReadOffset = 0;
		try {
			int bytesRead = 0;
			int bytesReadOffset = 0;

			while ((bytesRead=dcipherIn.read(buf)) >= 0) {
				System.out.println("bytesRead: " + bytesRead);
				System.out.println("bytesReadOffset: " + bytesReadOffset);

		    	os.write(buf, bytesReadOffset, bytesRead);
				bytesReadOffset = bytesReadOffset + bytesRead;

				// String message = new String(buf);
				// System.out.println("Message: " + message);
				//
				// System.out.println("------------------------------------");
			}

		os.close();

		dcipherIn.close();

		in.close();

		}catch (Exception e)
    	{
    		e.printStackTrace();
    	}


		String message = new String(buf);


		// -Print out the decrypt String to see if it matches the orignal message.
		System.out.println("Message: " + message);

		System.exit(0);
	}
}
